version: '3'

services:
  main:
    image: 'vaner-graphql-example'
    env_file:
      - .env
    ports:
      - ${PORT}:3000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_HOST: 'localhost'
    ports:
      - ${DB_PORT}:3306

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
