version: '3'

services:
  main:
    image: graphql-example
    env_file:
      - .env
    ports:
      - ${PORT}:3000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_HOST: 'localhost'
    ports:
      - ${DATABASE_PORT}:3306

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - ${DATABASE_PORT}:5432
